"""evm_verifier.py

Generate Solidity verifier(s) for EZKL proofs, including aggregated proofs.
Requires solc installed.

Usage:
  zk-generate-evm-verifier --key-dir prover/keys --out contracts/generated --aggregated
"""
import os, argparse, json
from pathlib import Path
import ezkl

def generate_verifier(key_dir: str, out_dir: str, aggregated: bool = False):
    """Generates a Solidity verifier contract for the EZKL circuit.

    This function uses the EZKL library to generate a Solidity contract that can
    verify proofs generated by the circuit. It supports both single and
    aggregated proofs.

    Args:
        key_dir: The directory containing the proving keys and settings.
        out_dir: The output directory for the generated Solidity code and ABI.
        aggregated: Whether to generate a verifier for aggregated proofs.

    Returns:
        A tuple containing the paths to the generated Solidity file and ABI JSON file.
    """
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    vk = os.path.join(key_dir, "vk.key")
    settings = os.path.join(key_dir, "settings.json")
    srs = os.path.join(key_dir, "kzg.srs")
    sol_path = os.path.join(out_dir, "EzklVerifier.sol")
    abi_path = os.path.join(out_dir, "EzklVerifier.abi.json")

    if aggregated and hasattr(ezkl, "create_evm_verifier_aggr"):
        ezkl.create_evm_verifier_aggr(
            aggregation_settings=settings,
            vk_path=vk,
            sol_code_path=sol_path,
            abi_path=abi_path,
            logrows=12,
            srs_path=srs
        )
    else:
        ezkl.create_evm_verifier(
            vk_path=vk,
            settings_path=settings,
            sol_code_path=sol_path,
            abi_path=abi_path,
            srs_path=srs
        )
    return sol_path, abi_path

def cli():
    """Command-line interface for generating the EVM verifier."""
    ap = argparse.ArgumentParser()
    ap.add_argument("--key-dir", default="prover/keys")
    ap.add_argument("--out", default="contracts/generated")
    ap.add_argument("--aggregated", action="store_true")
    args = ap.parse_args()
    sol, abi = generate_verifier(args.key_dir, args.out, args.aggregated)
    print(json.dumps({"solidity": sol, "abi": abi}, indent=2))

if __name__ == "__main__":
    cli()
